/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Connect_4;

import javax.swing.ImageIcon;

/**
 *
 * @author raedk
 */
public class Front extends javax.swing.JFrame {

    /**
     * Creates new form Front
     */
    public Front() {
        initComponents();
    }
    Board m=new Board();
      boolean f=true;
      int level,player;
      ImageIcon icon=new ImageIcon();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        p36 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        p37 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        p38 = new javax.swing.JLabel();
        p40 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        p39 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        p41 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        p42 = new javax.swing.JLabel();
        p29 = new javax.swing.JLabel();
        p30 = new javax.swing.JLabel();
        p31 = new javax.swing.JLabel();
        p32 = new javax.swing.JLabel();
        p33 = new javax.swing.JLabel();
        p34 = new javax.swing.JLabel();
        p35 = new javax.swing.JLabel();
        p23 = new javax.swing.JLabel();
        p27 = new javax.swing.JLabel();
        p25 = new javax.swing.JLabel();
        p22 = new javax.swing.JLabel();
        p26 = new javax.swing.JLabel();
        p24 = new javax.swing.JLabel();
        p28 = new javax.swing.JLabel();
        p15 = new javax.swing.JLabel();
        p20 = new javax.swing.JLabel();
        p18 = new javax.swing.JLabel();
        p17 = new javax.swing.JLabel();
        p19 = new javax.swing.JLabel();
        p21 = new javax.swing.JLabel();
        p16 = new javax.swing.JLabel();
        p12 = new javax.swing.JLabel();
        p13 = new javax.swing.JLabel();
        p11 = new javax.swing.JLabel();
        p9 = new javax.swing.JLabel();
        p14 = new javax.swing.JLabel();
        p8 = new javax.swing.JLabel();
        p10 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\4.png")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        p36.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\4.png")); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        p37.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\4.png")); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        p38.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p40.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setForeground(new java.awt.Color(51, 51, 255));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\4.png")); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 51, 255));
        jButton5.setForeground(new java.awt.Color(51, 51, 255));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\4.png")); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        p39.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        jButton6.setBackground(new java.awt.Color(51, 51, 255));
        jButton6.setForeground(new java.awt.Color(51, 51, 255));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\4.png")); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        p41.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        jButton7.setBackground(new java.awt.Color(51, 51, 255));
        jButton7.setForeground(new java.awt.Color(51, 51, 255));
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\4.png")); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        p42.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p29.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p30.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p31.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p32.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p33.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p34.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p35.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p23.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p27.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p25.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p22.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p26.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p24.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p28.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p15.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p20.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p18.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p17.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p19.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p21.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p16.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p12.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p13.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p11.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p9.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p14.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p8.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p10.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p5.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p4.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p1.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p2.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p7.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p6.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        p3.setIcon(new javax.swing.ImageIcon("C:\\Users\\raedk\\Downloads\\1.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p37)
                    .addComponent(p30)
                    .addComponent(p23)
                    .addComponent(p16)
                    .addComponent(p9)
                    .addComponent(p2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p38)
                    .addComponent(p31)
                    .addComponent(p24)
                    .addComponent(p17)
                    .addComponent(p10)
                    .addComponent(p3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p39)
                            .addComponent(p32)
                            .addComponent(p25)
                            .addComponent(p18)
                            .addComponent(p11)
                            .addComponent(p4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p41)
                    .addComponent(p34)
                    .addComponent(p27)
                    .addComponent(p20)
                    .addComponent(p13)
                    .addComponent(p6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p42)
                    .addComponent(p35)
                    .addComponent(p28)
                    .addComponent(p21)
                    .addComponent(p14)
                    .addComponent(p7))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p36)
                                .addGap(30, 30, 30)
                                .addComponent(p29)
                                .addGap(30, 30, 30)
                                .addComponent(p22)
                                .addGap(30, 30, 30)
                                .addComponent(p15)
                                .addGap(30, 30, 30)
                                .addComponent(p8)
                                .addGap(30, 30, 30)
                                .addComponent(p1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(p37)
                                .addGap(30, 30, 30)
                                .addComponent(p30)
                                .addGap(30, 30, 30)
                                .addComponent(p23)
                                .addGap(30, 30, 30)
                                .addComponent(p16)
                                .addGap(30, 30, 30)
                                .addComponent(p9)
                                .addGap(30, 30, 30)
                                .addComponent(p2)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(p38)
                            .addGap(30, 30, 30)
                            .addComponent(p31)
                            .addGap(30, 30, 30)
                            .addComponent(p24)
                            .addGap(30, 30, 30)
                            .addComponent(p17)
                            .addGap(30, 30, 30)
                            .addComponent(p10)
                            .addGap(30, 30, 30)
                            .addComponent(p3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(p39)
                        .addGap(30, 30, 30)
                        .addComponent(p32)
                        .addGap(30, 30, 30)
                        .addComponent(p25)
                        .addGap(30, 30, 30)
                        .addComponent(p18)
                        .addGap(30, 30, 30)
                        .addComponent(p11)
                        .addGap(30, 30, 30)
                        .addComponent(p4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(p40)
                        .addGap(30, 30, 30)
                        .addComponent(p33)
                        .addGap(30, 30, 30)
                        .addComponent(p26)
                        .addGap(30, 30, 30)
                        .addComponent(p19)
                        .addGap(30, 30, 30)
                        .addComponent(p12)
                        .addGap(30, 30, 30)
                        .addComponent(p5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(p41)
                        .addGap(30, 30, 30)
                        .addComponent(p34)
                        .addGap(30, 30, 30)
                        .addComponent(p27)
                        .addGap(30, 30, 30)
                        .addComponent(p20)
                        .addGap(30, 30, 30)
                        .addComponent(p13)
                        .addGap(30, 30, 30)
                        .addComponent(p6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(p42)
                        .addGap(30, 30, 30)
                        .addComponent(p35)
                        .addGap(30, 30, 30)
                        .addComponent(p28)
                        .addGap(30, 30, 30)
                        .addComponent(p21)
                        .addGap(30, 30, 30)
                        .addComponent(p14)
                        .addGap(30, 30, 30)
                        .addComponent(p7)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int y;
        y=m.setColumn(0);
        boolean v;
        v=m.getturn();
        if(y==5)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p1.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p1.setIcon(icon);}
        }
        if(y==4)
        {
             if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p8.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p8.setIcon(icon);}
        }
        if(y==3)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p15.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p15.setIcon(icon);}
        }
        if(y==2)
        {
            
           if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p22.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p22.setIcon(icon);}
        }
        if(y==1)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p29.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p29.setIcon(icon);}
        }
        if(y==0)
        {
           
        if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p36.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p36.setIcon(icon);}
        }
        m.checkforwin();
        m.checkDraw();
 if(m.getturn()==true&&player==1&&m.getf()==false)
            AI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int y;
        y=m.setColumn(1);
        boolean v;
        v=m.getturn();
        if(y==5)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p2.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p2.setIcon(icon);}
        }
        if(y==4)
        {
             if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p9.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p9.setIcon(icon);}
        }
        if(y==3)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p16.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p16.setIcon(icon);}
        }
        if(y==2)
        {
            
           if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p23.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p23.setIcon(icon);}
        }
        if(y==1)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p30.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p30.setIcon(icon);}
        }
        if(y==0)
        {
           
        if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p37.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p37.setIcon(icon);}
        }
        m.checkforwin();
         if(m.getturn()==true&&player==1&&m.getf()==false)
            AI();
         m.checkDraw();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int y;
        y=m.setColumn(2);
        boolean v;
        v=m.getturn();
        if(y==5)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p3.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p3.setIcon(icon);}
        }
        if(y==4)
        {
             if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p10.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p10.setIcon(icon);}
        }
        if(y==3)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p17.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p17.setIcon(icon);}
        }
        if(y==2)
        {
            
           if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p24.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p24.setIcon(icon);}
        }
        if(y==1)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p31.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p31.setIcon(icon);}
        }
        if(y==0)
        {
           
        if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p38.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p38.setIcon(icon);}
        }
        m.checkforwin();
        m.checkDraw();
         if(m.getturn()==true&&player==1&&m.getf()==false)
            AI();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           int y;
        y=m.setColumn(3);
        boolean v;
        v=m.getturn();
        if(y==5)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p4.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p4.setIcon(icon);}
        }
        if(y==4)
        {
             if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p11.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p11.setIcon(icon);}
        }
        if(y==3)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p18.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p18.setIcon(icon);}
        }
        if(y==2)
        {
            
           if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p25.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p25.setIcon(icon);}
        }
        if(y==1)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p32.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p32.setIcon(icon);}
        }
        if(y==0)
        {
           
        if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p39.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p39.setIcon(icon);}
        }
        m.checkforwin();
        m.checkDraw();
         if(m.getturn()==true&&player==1&&m.getf()==false)
            AI();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
             int y;
        y=m.setColumn(4);
        boolean v;
        v=m.getturn();
        if(y==5)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p5.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p5.setIcon(icon);}
        }
        if(y==4)
        {
             if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p12.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p12.setIcon(icon);}
        }
        if(y==3)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p19.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p19.setIcon(icon);}
        }
        if(y==2)
        {
            
           if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p26.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p26.setIcon(icon);}
        }
        if(y==1)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p33.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p33.setIcon(icon);}
        }
        if(y==0)
        {
           
        if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p40.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p40.setIcon(icon);}
        }
        m.checkforwin();
        m.checkDraw();
         if(m.getturn()==true&&player==1&&m.getf()==false)
            AI();
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
               int y;
        y=m.setColumn(5);
        boolean v;
        v=m.getturn();
        if(y==5)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p6.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p6.setIcon(icon);}
        }
        if(y==4)
        {
             if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p13.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p13.setIcon(icon);}
        }
        if(y==3)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p20.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p20.setIcon(icon);}
        }
        if(y==2)
        {
            
           if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p27.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p27.setIcon(icon);}
        }
        if(y==1)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p34.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p34.setIcon(icon);}
        }
        if(y==0)
        {
           
        if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p41.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p41.setIcon(icon);}
        }
        m.checkforwin();
        m.checkDraw();
         if(m.getturn()==true&&player==1&&m.getf()==false)
            AI();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                int y;
        y=m.setColumn(6);
        boolean v;
        v=m.getturn();
        if(y==5)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p7.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p7.setIcon(icon);}
        }
        if(y==4)
        {
             if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p14.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p14.setIcon(icon);}
        }
        if(y==3)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p21.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p21.setIcon(icon);}
        }
        if(y==2)
        {
            
           if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p28.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p28.setIcon(icon);}
        }
        if(y==1)
        {
            if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p35.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p35.setIcon(icon);}
        }
        if(y==0)
        {
           
        if(v==true){
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\3.png");
          p42.setIcon(icon);}
        else {
                icon=new ImageIcon("C:\\Users\\raedk\\Downloads\\2.png");
          p42.setIcon(icon);}
        }
        m.checkforwin();
        m.checkDraw();
        if(m.getturn()==true&&player==1&&m.getf()==false)
            AI();
    }//GEN-LAST:event_jButton7ActionPerformed
    public void AI(){
        int x=m.ai(level);
         switch(x){
             case 0: jButton1.doClick(); break;
                 case 1:jButton2.doClick();break;
                     case 2:jButton3.doClick();break;
                         case 3:jButton4.doClick();break;
                             case 4:jButton5.doClick();break;
                                 case 5:jButton6.doClick();break;
                                     case 6:jButton7.doClick();break;
         
         }
    }
    public void setPlayer(int x){
    player=x;
    }
      public void setLevel(int x){
    level=x;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p10;
    private javax.swing.JLabel p11;
    private javax.swing.JLabel p12;
    private javax.swing.JLabel p13;
    private javax.swing.JLabel p14;
    private javax.swing.JLabel p15;
    private javax.swing.JLabel p16;
    private javax.swing.JLabel p17;
    private javax.swing.JLabel p18;
    private javax.swing.JLabel p19;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p20;
    private javax.swing.JLabel p21;
    private javax.swing.JLabel p22;
    private javax.swing.JLabel p23;
    private javax.swing.JLabel p24;
    private javax.swing.JLabel p25;
    private javax.swing.JLabel p26;
    private javax.swing.JLabel p27;
    private javax.swing.JLabel p28;
    private javax.swing.JLabel p29;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p30;
    private javax.swing.JLabel p31;
    private javax.swing.JLabel p32;
    private javax.swing.JLabel p33;
    private javax.swing.JLabel p34;
    private javax.swing.JLabel p35;
    private javax.swing.JLabel p36;
    private javax.swing.JLabel p37;
    private javax.swing.JLabel p38;
    private javax.swing.JLabel p39;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p40;
    private javax.swing.JLabel p41;
    private javax.swing.JLabel p42;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel p8;
    private javax.swing.JLabel p9;
    // End of variables declaration//GEN-END:variables
}
